using Domain.Enums;

namespace Infrastructure.SeedManager.Demos;

/// <summary>Syrian-market demo definitions for technical products, commercial offerings, and VAS.</summary>
internal static class DemoSyrianTelecomCatalog
{
    internal sealed record ProductDef(
        string ServiceCode,
        string Name,
        double UnitPrice,
        string? SubscriptionTypeCode = null);

    internal sealed record OfferingDef(
        string Code,
        string Name,
        string NameEn,
        string Description,
        string ProductServiceCode,
        string SubscriptionTypeCode,
        int SortOrder,
        PaymentType? PaymentType,
        string? BadgeColor,
        (ServiceComponentType type, string label, decimal? quota, string? unit, bool unlimited)[] Components,
        (PricePlanType planType, decimal price, decimal? activationFee, int? validityDays, bool isDefault)[] Plans);

    internal sealed record VasDef(
        string ServiceCode,
        string NameAr,
        string NameEn,
        string Description,
        decimal MonthlyFee,
        int SortOrder);

    public static readonly ProductDef[] Products =
    [
        new("YAHALA_SHABAB", "يا هلا شباب (شحن)", 150, "PREPAID"),
        new("YAHALA_PLUS", "يا هلا بلس (شحن)", 220, "PREPAID"),
        new("SHAM_CARD", "شام كارد (شحن)", 100, "PREPAID"),
        new("SHABAB_PRE", "باقة شباب (شحن)", 180, "PREPAID"),
        new("SOCIAL_UNL", "سوشال بلا حدود (شحن)", 120, "PREPAID"),
        new("RAMADAN_PRE", "رمضان مبارك (شحن موسمي)", 90, "PREPAID"),
        new("PRE_UNL_VOICE", "دقائق مفتوحة شحن", 350, "PREPAID"),
        new("SABA_10GB", "سَبَا 10GB", 35, "PREPAID"),
        new("NIGHT_UNL", "نت ليلي بلا حدود", 45, "PREPAID"),
        new("SYR_MIX_HYBRID", "سيريتل ميكس (مدمج)", 250, "HYBRID"),
        new("MIX_1000", "سيريتل ميكس 1000", 380, "HYBRID"),
        new("MIX_PLUS", "ميكس بلس", 320, "HYBRID"),
        new("FAMILY_MIX", "عائلة ميكس", 290, "HYBRID"),
        new("SUPER_MIX", "سوبر ميكس", 450, "HYBRID"),
        new("SYR_POST_PLAT", "خط فاتورة — بلاتيني", 400, "POSTPAID"),
        new("POST_CLASSIC", "فاتورة كلاسيك", 280, "POSTPAID"),
        new("POST_100", "فاتورة 100", 180, "POSTPAID"),
        new("POST_200", "فاتورة 200", 320, "POSTPAID"),
        new("POST_GOLD", "فاتورة ذهبي", 520, "POSTPAID"),
        new("POST_SILVER", "فاتورة فضي", 240, "POSTPAID"),
        new("BUSINESS_PRO_50", "بزنس برو 50", 1200, "POSTPAID"),
        new("BIZ_STANDARD", "بزنس ستاندرد", 850, "POSTPAID"),
        new("FLEET_CORP", "أسطول الشركات", 2500, "POSTPAID"),
        new("ADSL_HOME", "ADSL منزلي", 65, null),
        new("FIBER_100", "فايبر 100 ميجا", 95, null),
        new("FIXED_VOICE", "خط ثابت منزلي", 55, null),
        new("HW_ROUTER_5G", "راوتر 5G", 0, null),
        new("HW_WINGLE", "وينجل 4G", 0, null),
        new("SRV_ACTIVATION", "رسوم تفعيل خط", 25, null),
        new("SRV_PROMO_DISC", "خصم ترويجي", 0, null),
    ];

    public static readonly OfferingDef[] Offerings =
    [
        new("YA_HALA_30", "يا هلا", "Ya Hala", "الباقة الأشهر في سوريا — شحن اقتصادي.", "YAHALA_SHABAB", "PREPAID", 1, PaymentType.Prepaid, "success",
            [(ServiceComponentType.Voice, "200 دقيقة محلية", 200m, "minutes", false), (ServiceComponentType.Data, "3 جيجا", 3m, "GB", false), (ServiceComponentType.Sms, "50 رسالة", 50m, "SMS", false)],
            [(PricePlanType.Monthly, 15000m, null, 30, true), (PricePlanType.Weekly, 5000m, null, 7, false)]),
        new("YA_HALA_PLUS", "يا هلا بلس", "Ya Hala Plus", "شحن موسّع للاستخدام اليومي.", "YAHALA_PLUS", "PREPAID", 2, PaymentType.Prepaid, "success",
            [(ServiceComponentType.Voice, "400 دقيقة محلية", 400m, "minutes", false), (ServiceComponentType.Data, "8 جيجا", 8m, "GB", false), (ServiceComponentType.Sms, "100 رسالة", 100m, "SMS", false)],
            [(PricePlanType.Monthly, 22000m, null, 30, true)]),
        new("SHAM_CARD", "شام كارد", "Sham Card", "بطاقة شحن مرنة للطلاب.", "SHAM_CARD", "PREPAID", 3, PaymentType.Prepaid, "info",
            [(ServiceComponentType.Voice, "100 دقيقة", 100m, "minutes", false), (ServiceComponentType.Data, "2 جيجا", 2m, "GB", false)],
            [(PricePlanType.Monthly, 10000m, null, 30, true), (PricePlanType.Daily, 800m, null, 1, false)]),
        new("SHABAB", "شباب", "Shabab", "باقة الشباب — بيانات وسوشال.", "SHABAB_PRE", "PREPAID", 4, PaymentType.Prepaid, "primary",
            [(ServiceComponentType.Data, "15 جيجا", 15m, "GB", false), (ServiceComponentType.Voice, "150 دقيقة", 150m, "minutes", false)],
            [(PricePlanType.Monthly, 18000m, null, 30, true)]),
        new("SOCIAL_UNL", "سوشال بلا حدود", "Social Unlimited", "واتساب وفيسبوك وإنستغرام بلا حدود ضمن الحصة.", "SOCIAL_UNL", "PREPAID", 5, PaymentType.Prepaid, "warning",
            [(ServiceComponentType.Data, "25 جيجا عامة", 25m, "GB", false), (ServiceComponentType.Vas, "سوشال ميديا مجاناً", null, null, true)],
            [(PricePlanType.Monthly, 12000m, null, 30, true)]),
        new("RAMADAN_PRE", "رمضان مبارك", "Ramadan Bundle", "عرض موسمي للشحن.", "RAMADAN_PRE", "PREPAID", 6, PaymentType.Prepaid, "secondary",
            [(ServiceComponentType.Voice, "300 دقيقة", 300m, "minutes", false), (ServiceComponentType.Data, "5 جيجا", 5m, "GB", false)],
            [(PricePlanType.Monthly, 9000m, null, 30, true)]),
        new("PRE_UNL_VOICE", "دقائق مفتوحة شحن", "Prepaid Unlimited Voice", "دقائق محلية غير محدودة + بيانات أساسية.", "PRE_UNL_VOICE", "PREPAID", 7, PaymentType.Prepaid, "dark",
            [(ServiceComponentType.Voice, "دقائق محلية غير محدودة", null, "minutes", true), (ServiceComponentType.Data, "1 جيجا", 1m, "GB", false)],
            [(PricePlanType.Monthly, 35000m, null, 30, true)]),
        new("UNLIM_NET_100", "نت بلا حدود", "Unlimited Net", "بيانات ضخمة لعشاق الإنترنت.", "SABA_10GB", "PREPAID", 8, PaymentType.Prepaid, "info",
            [(ServiceComponentType.Voice, "50 دقيقة", 50m, "minutes", false), (ServiceComponentType.Data, "100 جيجا", 100m, "GB", false)],
            [(PricePlanType.Monthly, 20000m, null, 30, true), (PricePlanType.Daily, 1200m, null, 1, false)]),
        new("SABA_10", "سَبَا 10", "Saba 10", "باقة بيانات فقط.", "SABA_10GB", "PREPAID", 9, PaymentType.Prepaid, null,
            [(ServiceComponentType.Data, "10 جيجا", 10m, "GB", false)],
            [(PricePlanType.Monthly, 3500m, null, 30, true)]),
        new("NIGHT_UNL", "نت ليلي بلا حدود", "Night Unlimited", "إنترنت ليلي غير محدود (12ص–6ص).", "NIGHT_UNL", "PREPAID", 10, PaymentType.Prepaid, null,
            [(ServiceComponentType.Data, "ليلي غير محدود", null, "GB", true)],
            [(PricePlanType.Monthly, 4500m, null, 30, true)]),
        new("MIX_500", "سيريتل ميكس 500", "Syriatel Mix 500", "باقة مدمجة شاملة.", "SYR_MIX_HYBRID", "HYBRID", 11, PaymentType.Hybrid, "primary",
            [(ServiceComponentType.Voice, "500 دقيقة", 500m, "minutes", false), (ServiceComponentType.Data, "20 جيجا", 20m, "GB", false), (ServiceComponentType.Sms, "100 رسالة", 100m, "SMS", false), (ServiceComponentType.Vas, "كاشف الأرقام", null, null, true)],
            [(PricePlanType.Monthly, 25000m, 5000m, 30, true)]),
        new("MIX_1000", "سيريتل ميكس 1000", "Mix 1000", "ميكس للمستخدمين الكثيفين.", "MIX_1000", "HYBRID", 12, PaymentType.Hybrid, "primary",
            [(ServiceComponentType.Voice, "1000 دقيقة", 1000m, "minutes", false), (ServiceComponentType.Data, "40 جيجا", 40m, "GB", false), (ServiceComponentType.Sms, "200 رسالة", 200m, "SMS", false)],
            [(PricePlanType.Monthly, 38000m, 5000m, 30, true)]),
        new("MIX_PLUS", "ميكس بلس", "Mix Plus", "ميكس مع VAS مجانية.", "MIX_PLUS", "HYBRID", 13, PaymentType.Hybrid, "warning",
            [(ServiceComponentType.Voice, "750 دقيقة", 750m, "minutes", false), (ServiceComponentType.Data, "30 جيجا", 30m, "GB", false), (ServiceComponentType.Vas, "بريد صوتي + انتظار", null, null, true)],
            [(PricePlanType.Monthly, 32000m, 3000m, 30, true)]),
        new("FAMILY_MIX", "عائلة ميكس", "Family Mix", "خط رئيسي + خطوط عائلية مشتركة.", "FAMILY_MIX", "HYBRID", 14, PaymentType.Hybrid, "success",
            [(ServiceComponentType.Voice, "1500 دقيقة مشتركة", 1500m, "minutes", false), (ServiceComponentType.Data, "60 جيجا مشتركة", 60m, "GB", false)],
            [(PricePlanType.Monthly, 29000m, 4000m, 30, true)]),
        new("SUPER_MIX", "سوبر ميكس", "Super Mix", "أقصى حصة ميكس للأعمال الصغيرة.", "SUPER_MIX", "HYBRID", 15, PaymentType.Hybrid, "danger",
            [(ServiceComponentType.Voice, "2000 دقيقة", 2000m, "minutes", false), (ServiceComponentType.Data, "80 جيجا", 80m, "GB", false), (ServiceComponentType.International, "50 دقيقة دولية", 50m, "minutes", false)],
            [(PricePlanType.Monthly, 45000m, 6000m, 30, true)]),
        new("PLATINUM_VIP", "بلاتيني", "Platinum", "فاتورة VIP متميزة.", "SYR_POST_PLAT", "POSTPAID", 16, PaymentType.Postpaid, "gold",
            [(ServiceComponentType.Voice, "دقائق محلية غير محدودة", null, "minutes", true), (ServiceComponentType.Data, "50 جيجا", 50m, "GB", false), (ServiceComponentType.International, "100 دقيقة دولية", 100m, "minutes", false), (ServiceComponentType.Vas, "كاشف + بريد + تجوال مخفض", null, null, true)],
            [(PricePlanType.Monthly, 75000m, 0m, 30, true)]),
        new("POST_CLASSIC", "فاتورة كلاسيك", "Postpaid Classic", "فاتورة شهرية قياسية.", "POST_CLASSIC", "POSTPAID", 17, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "300 دقيقة", 300m, "minutes", false), (ServiceComponentType.Data, "12 جيجا", 12m, "GB", false)],
            [(PricePlanType.Monthly, 28000m, 0m, 30, true)]),
        new("POST_100", "فاتورة 100", "Invoice 100", "باقة فاتورة اقتصادية.", "POST_100", "POSTPAID", 18, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "200 دقيقة", 200m, "minutes", false), (ServiceComponentType.Data, "8 جيجا", 8m, "GB", false)],
            [(PricePlanType.Monthly, 18000m, 0m, 30, true)]),
        new("POST_200", "فاتورة 200", "Invoice 200", "فاتورة متوسطة.", "POST_200", "POSTPAID", 19, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "400 دقيقة", 400m, "minutes", false), (ServiceComponentType.Data, "18 جيجا", 18m, "GB", false)],
            [(PricePlanType.Monthly, 32000m, 0m, 30, true)]),
        new("POST_GOLD", "فاتورة ذهبي", "Gold Postpaid", "فاتورة متميزة.", "POST_GOLD", "POSTPAID", 20, PaymentType.Postpaid, "warning",
            [(ServiceComponentType.Voice, "800 دقيقة", 800m, "minutes", false), (ServiceComponentType.Data, "35 جيجا", 35m, "GB", false), (ServiceComponentType.International, "60 دقيقة دولية", 60m, "minutes", false)],
            [(PricePlanType.Monthly, 52000m, 0m, 30, true)]),
        new("POST_SILVER", "فاتورة فضي", "Silver Postpaid", "فاتورة متوسطة-منخفضة.", "POST_SILVER", "POSTPAID", 21, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "250 دقيقة", 250m, "minutes", false), (ServiceComponentType.Data, "10 جيجا", 10m, "GB", false)],
            [(PricePlanType.Monthly, 24000m, 0m, 30, true)]),
        new("BIZ_PLUS_FLEET", "بزنس بلس", "Business Plus", "أسطول شركات مع راوتر 5G.", "BUSINESS_PRO_50", "POSTPAID", 22, PaymentType.Postpaid, "dark",
            [(ServiceComponentType.Voice, "1000 دقيقة مشتركة", 1000m, "minutes", false), (ServiceComponentType.Data, "200 جيجا مشتركة", 200m, "GB", false), (ServiceComponentType.Equipment, "راوتر 5G (12 شهر)", 1m, "unit", false)],
            [(PricePlanType.Monthly, 120000m, 15000m, 30, true)]),
        new("BIZ_STANDARD", "بزنس ستاندرد", "Business Standard", "شركات صغيرة ومتوسطة.", "BIZ_STANDARD", "POSTPAID", 23, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "600 دقيقة", 600m, "minutes", false), (ServiceComponentType.Data, "80 جيجا", 80m, "GB", false)],
            [(PricePlanType.Monthly, 85000m, 8000m, 30, true)]),
        new("FLEET_CORP", "أسطول الشركات", "Corporate Fleet", "إدارة مركزية لخطوط المؤسسات.", "FLEET_CORP", "POSTPAID", 24, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "3000 دقيقة مشتركة", 3000m, "minutes", false), (ServiceComponentType.Data, "500 جيجا مشتركة", 500m, "GB", false), (ServiceComponentType.International, "500 دقيقة دولية", 500m, "minutes", false)],
            [(PricePlanType.Monthly, 250000m, 25000m, 30, true)]),
        new("ADSL_HOME", "ADSL منزلي", "Home ADSL", "إنترنت منزلي ADSL.", "ADSL_HOME", "POSTPAID", 25, PaymentType.Postpaid, null,
            [(ServiceComponentType.Data, "20 ميجا تنزيل", 20m, "Mbps", false)],
            [(PricePlanType.Monthly, 65000m, 10000m, 30, true)]),
        new("FIBER_100", "فايبر 100", "Fiber 100", "ألياف بصرية 100 ميجا.", "FIBER_100", "POSTPAID", 26, PaymentType.Postpaid, null,
            [(ServiceComponentType.Data, "100 ميجا", 100m, "Mbps", false), (ServiceComponentType.Equipment, "مودم فايبر", 1m, "unit", false)],
            [(PricePlanType.Monthly, 95000m, 15000m, 30, true)]),
        new("FIXED_VOICE", "خط ثابت منزلي", "Fixed Line", "هاتف ثابت + مكالمات محلية.", "FIXED_VOICE", "POSTPAID", 27, PaymentType.Postpaid, null,
            [(ServiceComponentType.Voice, "مكالمات محلية غير محدودة", null, "minutes", true)],
            [(PricePlanType.Monthly, 55000m, 5000m, 30, true)]),
    ];

    public static readonly VasDef[] VasServices =
    [
        new("VAS_ECLIP", "إشعار المكالمات الفائتة (eClip)", "Missed Call Alert", "إشعار SMS عند فقدان مكالمة.", 100m, 1),
        new("VAS_SYRIATEL_CASH", "محفظة سيريتل كاش", "SyriaTel Cash", "محفظة الدفع الإلكتروني.", 0m, 2),
        new("VAS_ROAMING_INT", "التجوال الدولي", "International Roaming", "تجوال خارج سوريا.", 250m, 3),
        new("VAS_CALLER_ID", "كاشف الأرقام", "Caller ID", "عرض رقم المتصل.", 75m, 4),
        new("VAS_VOICEMAIL", "البريد الصوتي", "Voicemail", "رسائل صوتية عند عدم الرد.", 50m, 5),
        new("VAS_CALL_WAIT", "انتظار المكالمات", "Call Waiting", "تنبيه بمكالمة واردة أثناء المكالمة.", 40m, 6),
        new("VAS_CALL_FWD", "تحويل المكالمات", "Call Forwarding", "تحويل للخط أو البريد الصوتي.", 40m, 7),
        new("VAS_DATA_BOOST", "تعزيز بيانات يومي", "Daily Data Boost", "1 جيجا إضافية لمدة 24 ساعة.", 150m, 8),
        new("VAS_RINGBACK", "نغمة الانتظار", "Ringback Tone", "نغمة مخصصة للمتصلين.", 120m, 9),
        new("VAS_SPORTS_ALERT", "تنبيهات رياضية", "Sports Alerts", "نتائج مباريات SMS.", 80m, 10),
        new("VAS_PRAYER_SMS", "مواقيت الصلاة", "Prayer Times SMS", "تذكير يومي بمواقيت الصلاة.", 60m, 11),
        new("VAS_PARENTAL", "رقابة أبوية", "Parental Control", "تصفية محتوى للأطفال.", 90m, 12),
        new("VAS_MULTI_SIM", "خط إضافي / eSIM", "Multi-SIM", "خط ثانٍ على نفس الحساب.", 200m, 13),
        new("VAS_INTL_PACK", "باقة دولية 50", "Intl Pack 50", "50 دقيقة دولية شهرياً.", 300m, 14),
        new("VAS_ROAM_ARAB", "تجوال عربي", "Arab Roaming", "تجوال مخفّض في الدول العربية.", 180m, 15),
        new("VAS_MOBILE_INS", "تأمين الجهاز", "Mobile Insurance", "تغطية ضد الكسر والسرقة.", 400m, 16),
        new("VAS_ANTIVIRUS", "حماية الهاتف", "Mobile Security", "مكافحة فيروسات وتصيّد.", 110m, 17),
        new("VAS_MUSIC", "موسيقى بلا حدود", "Music Streaming", "بث موسيقى محلي وعالمي.", 130m, 18),
        new("VAS_VIDEO", "فيديو بلا حدود", "Video Pass", "بث فيديو ضمن الحصة.", 160m, 19),
        new("VAS_BIZ_VPN", "VPN أعمال", "Business VPN", "وصول آمن لشبكة الشركة.", 350m, 20),
        new("VAS_CORP_SMS", "SMS جماعي للشركات", "Corporate SMS", "رسائل جماعية للعملاء.", 500m, 21),
        new("VAS_4G_PRIORITY", "أولوية 4G", "4G Priority", "أولوية في ازدحام الشبكة.", 95m, 22),
        new("VAS_NIGHT_DATA", "بيانات ليلية", "Night Data Add-on", "إضافة بيانات ليلية.", 70m, 23),
    ];

    public static string HlrTemplate(string serviceCode) =>
        $"ADD-SUPPLEMENTARY: MSISDN={{MSISDN}}; SVC={serviceCode}; ACTION={{ACTION}}";
}
